apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert
spec:
  commonName: wordpress.duckbank.de
  dnsNames:
  - wordpress.duckbank.de
  issuerRef:
    name: ca-issuer-selfsigned
    kind: Issuer
  secretName: wordpress-tls