apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wordpress
spec:
  virtualhost:
    fqdn: wordpress.duckbank.de
    tls:
      secretName: wordpress-tls
  routes:
  - conditions:
    - prefix: /
    services:
    - name: wordpress
      port: 80,443